version: '3.4'
services:
  database:
    image: postgres:9.6
    container_name: lava_postgres
    environment:
      POSTGRES_USER: lavaserver
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  squid:
    image: datadog/squid
    container_name: lava_squid
    volumes:
      - squid:/var/spool/squid
      - ./squid/squid.conf:/etc/squid/squid.conf
    ports:
      - 3128:3128
    restart: always

  server:
    #image: lavasoftware/amd64-lava-server:2019.01

    # Use an updated entrypoint; this is necessary to run provision.sh at boot time
    # See https://git.lavasoftware.org/lava/pkg/docker/merge_requests/10
    build:
      context: ./server-docker

    container_name: lava_server
    ports:
      - 80:80
    volumes:
      - joboutput:/var/lib/lava-server/default/media/job-output
      - ./server-overlay/etc/lava-server/settings.conf:/etc/lava-server/settings.conf
      - ./server-overlay/etc/lava-server/instance.conf:/etc/lava-server/instance.conf
      - ./server-overlay/etc/lava-server/dispatcher-config/health-checks:/etc/lava-server/dispatcher-config/health-checks
      - ./server-overlay/etc/lava-server/dispatcher-config/devices:/etc/lava-server/dispatcher-config/devices
      - ./server-overlay/root/provision.sh:/root/provision.sh
      - ./server-overlay/etc/lava-server/dispatcher-config/device-types/base.jinja2:/etc/lava-server/dispatcher-config/device-types/base.jinja2
      - ./server-overlay/etc/lava-server/dispatcher.d/:/etc/lava-server/dispatcher.d/
    depends_on:
      - database
    restart: always

  dispatcher:
    image: lavasoftware/amd64-lava-dispatcher:2019.01
    container_name: lava_dispatcher
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    environment:
      - "DISPATCHER_HOSTNAME=--hostname=dispatcher"
      - "LOGGER_URL=tcp://server:5555" # url to send logs
      - "MASTER_URL=tcp://server:5556" # url of lava master
    volumes:
      - ./dispatcher-overlay/opt:/opt
      - /boot:/boot:ro
      - /lib/modules:/lib/modules:ro
      - nfsd:/var/lib/lava/dispatcher/tmp
      - tftp:/srv/tftp
      - ./dispatcher-overlay/etc/lava-dispatcher:/etc/lava-dispatcher
    restart: always

  ser2net:
    image: danrue/ser2net:3.5
    container_name: lava_ser2net
    volumes:
      - ./ser2net/ser2net.conf:/etc/ser2net.conf
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0 # beaglebone-black
      - /dev/serial/by-id/usb-FTDI_TTL232R-3V3_FT9ROPBL-if00-port0 # x15
      #- /dev/serial/by-id/usb-FTDI_USB_Serial_Converter_FTB6SPL3-if00-port0 # rock960
    restart: always


  tftpd-hpa:
    image: danrue/tftpd-hpa:5.2
    container_name: lava_tftp
    ports:
      - 69:69/udp
    volumes:
      - tftp:/srv/tftp
    restart: always


  nfsd:
    image: erichough/nfs-server
    container_name: lava_nfsd
    ports:
      - 2049:2049 #nfsv4
    volumes:
      - nfsd:/var/lib/lava/dispatcher/tmp
      - ./nfsd/exports:/etc/exports
    cap_add:
      - SYS_ADMIN

volumes:
  pgdata:
    name: lava-server-pgdata
  squid:
    name: lava-squid-cache
  joboutput:
    name: lava-server-job-output
  tftp:
    name: lava-tftp
  nfsd:
    name: lava-nfsd
